const data = {
  poleDate: "10/Oct/2020",
  tableList: [
    {
      title: "HMR Institute of Technology & Management (HMRITM)",
      location: " New Delhi, Delhi Ncr ( India )",
      fees: "₹ 17.26 Lakh - ₹ 27.26 Lakh",
      type: "PGD/MSC",
      mode: "Full time/ Regular",
      duration: "1-3 year",
      no: "15+",
    },
    {
      title: "HMR Institute of Technology & Management (HMRITM)",
      location: " New Delhi, Delhi Ncr ( India )",
      fees: "₹ 17.26 Lakh - ₹ 27.26 Lakh",
      type: "PGD/MSC",
      mode: "Full time/ Regular",
      duration: "1-3 year",
      no: "15+",
    },
    {
      title: "HMR Institute of Technology & Management (HMRITM)",
      location: " New Delhi, Delhi Ncr ( India )",
      fees: "₹ 17.26 Lakh - ₹ 27.26 Lakh",
      type: "PGD/MSC",
      mode: "Full time/ Regular",
      duration: "1-3 year",
      no: "15+",
    },
    {
      title: "HMR Institute of Technology & Management (HMRITM)",
      location: " New Delhi, Delhi Ncr ( India )",
      fees: "₹ 17.26 Lakh - ₹ 27.26 Lakh",
      type: "PGD/MSC",
      mode: "Full time/ Regular",
      duration: "1-3 year",
      no: "15+",
    },
    {
      title: "HMR Institute of Technology & Management (HMRITM)",
      location: " New Delhi, Delhi Ncr ( India )",
      fees: "₹ 17.26 Lakh - ₹ 27.26 Lakh",
      type: "PGD/MSC",
      mode: "Full time/ Regular",
      duration: "1-3 year",
      no: "15+",
    },
  ],
  helpQuestionList: [
    "Need help with Visa/Forex",
    "Didn't find what you're looking for ?",
    "Need help with Accommodation",
    "Need help with Loan",
  ],
  testimonials: [
    {
      heading: "Marta B. on Aug 29, 20201",
      title: '"Great service, very professional"',
      body: '"I had multiple versions of my resume and none of them produced expected results. After I spoke with Deepika and received my... "',
    },
    {
      heading: "Marta B. on Aug 29, 20202",
      title: '"Great service, very professional"',
      body: '"I had multiple versions of my resume and none of them produced expected results. After I spoke with Deepika and received my... "',
    },
    {
      heading: "Marta B. on Aug 29, 2023033",
      title: '"Great service, very professional"',
      body: '"I had multiple versions of my resume and none of them produced expected results. After I spoke with Deepika and received my... "',
    },
    {
      heading: "Marta B. on Aug 29, 20204",
      title: '"Great service, very professional"',
      body: '"I had multiple versions of my resume and none of them produced expected results. After I spoke with Deepika and received my... "',
    },
    {
      heading: "Marta B. on Aug 29, 202054",
      title: '"Great service, very professional"',
      body: '"I had multiple versions of my resume and none of them produced expected results. After I spoke with Deepika and received my... "',
    },
    {
      heading: "Marta B. on Aug 29, 2020",
      title: '"Great service, very professional"',
      body: '"I had multiple versions of my resume and none of them produced expected results. After I spoke with Deepika and received my... "',
    },
    {
      heading: "Marta B. on Aug 29, 2020",
      title: '"Great service, very professional"',
      body: '"I had multiple versions of my resume and none of them produced expected results. After I spoke with Deepika and received my... "',
    },
    {
      heading: "Marta B. on Aug 29, 2020",
      title: '"Great service, very professional"',
      body: '"I had multiple versions of my resume and none of them produced expected results. After I spoke with Deepika and received my... "',
    },
    {
      heading: "Marta B. on Aug 29, 2020",
      title: '"Great service, very professional"',
      body: '"I had multiple versions of my resume and none of them produced expected results. After I spoke with Deepika and received my... "',
    },
    {
      heading: "Marta B. on Aug 29, 2020",
      title: '"Great service, very professional"',
      body: '"I had multiple versions of my resume and none of them produced expected results. After I spoke with Deepika and received my... "',
    },
  ],
  programDetails: [
    {
      name: "Post Graduate Program in Management (PGPM)",
      duration: "3 Year",
      mode: "Part Time, Regular",
      graduation: "Post Graduation",
      date: "August 22",
      fees: "approx. 17.26lakh",
      eligibility: "12th Pass, Graduate",
      visa: "Give your career a boost with sea&beyond",
      scholarshipAvailable: "Yes",
    },
    {
      name: "Post Graduate Program in Management (PGPM)",
      duration: "3 Year",
      mode: "Part Time, Regular",
      graduation: "Post Graduation",
      date: "August 22",
      fees: "approx. 17.26lakh",
      eligibility: "12th Pass, Graduate",
      visa: "Give your career a boost with sea&beyond",
      scholarshipAvailable: "Yes",
    },
    {
      name: "Post Graduate Program in Management (PGPM)",
      duration: "3 Year",
      mode: "Part Time, Regular",
      graduation: "Post Graduation",
      date: "August 22",
      fees: "approx. 17.26lakh",
      eligibility: "12th Pass, Graduate",
      visa: "Give your career a boost with sea&beyond",
      scholarshipAvailable: "Yes",
    },
    {
      name: "Post Graduate Program in Management (PGPM)",
      duration: "3 Year",
      mode: "Part Time, Regular",
      graduation: "Post Graduation",
      date: "August 22",
      fees: "approx. 17.26lakh",
      eligibility: "12th Pass, Graduate",
      visa: "Give your career a boost with sea&beyond",
      scholarshipAvailable: "Yes",
    },
    {
      name: "Post Graduate Program in Management (PGPM)",
      duration: "3 Year",
      mode: "Part Time, Regular",
      graduation: "Post Graduation",
      date: "August 22",
      fees: "approx. 17.26lakh",
      eligibility: "12th Pass, Graduate",
      visa: "Give your career a boost with sea&beyond",
      scholarshipAvailable: "Yes",
    },
  ],
  upcomingEvent: [
    {
      name: "Find your pole star (2nd batch)",
      type: "Tournament",
      seatsRemaining: 10,
      totalSeats: 120,
      date: "09th Jan",
      time: "2:30 PM (IST)",
    },
    {
      name: "Find your pole star (2nd batch)",
      type: "Webinar",
      seatsRemaining: 10,
      totalSeats: 120,
      date: "09th Jan",
      time: "2:30 PM (IST)",
    },
    {
      name: "Find your pole star (2nd batch)",
      type: "Coaching",
      seatsRemaining: 10,
      totalSeats: 120,
      date: "09th Jan",
      time: "2:30 PM (IST)",
    },
    {
      name: "Find your pole star (2nd batch)",
      type: "Training",
      seatsRemaining: 10,
      totalSeats: 120,
      date: "09th Jan",
      time: "2:30 PM (IST)",
    },
  ],
  jobs: [
    {
      name: "Operations Manager    ",
      location: "New Delhi, Delhi Ncr ( India )",
      type: "Full Time",
      position: "Crewing department",
      experience: "6-8 years",
      desc: "We are hiring for a master mariner for agency operations, looking for: -Master Mariner with Bulk Carrier / Container ships background..",
    },
    {
      name: "Operations Manager    ",
      location: "New Delhi, Delhi Ncr ( India )",
      type: "Part Time",
      position: "Crewing department",
      experience: "6-8 years",
      desc: "We are hiring for a master mariner for agency operations, looking for: -Master Mariner with Bulk Carrier / Container ships background..",
    },
    {
      name: "Operations Manager    ",
      location: "New Delhi, Delhi Ncr ( India )",
      type: "Internship",
      position: "Crewing department",
      experience: "6-8 years",
      desc: "We are hiring for a master mariner for agency operations, looking for: -Master Mariner with Bulk Carrier / Container ships background..",
    },
    {
      name: "Operations Manager    ",
      location: "New Delhi, Delhi Ncr ( India )",
      type: "Contractual",
      position: "Crewing department",
      experience: "6-8 years",
      desc: "We are hiring for a master mariner for agency operations, looking for: -Master Mariner with Bulk Carrier / Container ships background..",
    },
    {
      name: "Operations Manager    ",
      location: "New Delhi, Delhi Ncr ( India )",
      type: "Full Time",
      position: "Crewing department",
      experience: "6-8 years",
      desc: "We are hiring for a master mariner for agency operations, looking for: -Master Mariner with Bulk Carrier / Container ships background..",
    },
  ],
  marinerInfo1: [
    "47% mariners login on LinkedIn everyday",
    "44% mariners update their LinkedIn account even quarter",
    "58% Mariners think a good LinkedIn profile has helped them in their career (better jobs and new learning's) ",
    "42% Mariners received more than two job opportunities through LinkedIn",
  ],
  marinerInfo2: [
    " No matter how many complex projects you have managed or ships you have sailed, its not easy to write about yourselves",
    " Making a personal brand recognizable on professional social media is becoming imperative",
    " You want to get head hunted by the recruiters or placement companies",
    " You want to keep yourself updated and want to share your opinions",
    " You want recognition",
  ],
  entry1: ["Evaluation on 10-15 parameters", "Comprehensive report", "Ranking of profile with reasoning"],
  entry2: ["Profile writing with 100% confidentiality", "Includes Job Profile, Summary", " 3-5 days of Turnover",],
  whyReasons: [
    " Most number of LinkedIn followers for a company into our domain",
    "Helped multiple companies and persons develop their brand",
    "Team of mariners and HR professionals",
  ],
};

export default data;
